### ISSUE TITLE
DenseTNT

### ISSUE THREAD

**Issue by Ethan-Zheng136** [alfredgu001324/MapBEVPrediction#3]
Hello, I’m back with more questions! I’m really interested in your research in this area. I’ve already fully validated your previous CVPR model, and the metrics are spot on. You guys are truly amazing. Now, I’m studying your latest ECCV paper on BEV, but it seems like your DenseTNT model hasn’t been open-sourced yet. I’m really eager to learn from it. Could I ask when you plan to open-source it?

**Comment by alfredgu001324** [comment]
Yea thanks for reaching out... sorry for so procrastinating on this. Now that I have finished my internship and back to school, I think I would have more time to work on this! I will try to tidy up my code and validate them within the next week or so (at least before ECCV starts I should have them out for open-source haha). Thank you so much for your support!!

**Comment by Ethan-Zheng136** [comment]
thank you！
